name: CI
on: push
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Update theme
        # (Optional)If you have the theme added as submodule, you can pull it and use the most updated version
        run: git submodule update --init --recursive

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build
        # remove --minify tag if you do not need it
        # docs: https://gohugo.io/hugo-pipes/minification/
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          # ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          # personal_token: ${{ secrets.ACCESS_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          external_repository: orange-sugar/orange-sugar.github.io
          publish_dir: ./public
          #   keep_files: true
          user_name: orange-sugar 
          user_email: 1565188353@qq.com
          publish_branch: main
        #   cname: example.com
